export const QuestionPack = [
  {
    id: 1,
    question: "What city is known as 'The Eternal City'?",
    options: ["(A) Rome", "(B) London", "(C) New york", "(D) Manchester"],
    answer: "(A) Rome",
    category: "general",
  },
  {
    id: 2,
    question: "In what country is the Chernobyl nuclear plant located?",
    options: ["(A) Ukraine", "(B) USA", "(C) Denmark", "(D) Russia"],
    answer: "(A) Ukraine",
    category: "general",
  },

  {
    id: 3,
    question: "Compared to their body weight, what animal is the strongest?",
    options: ["(A) Elephant", "(B) Ant", "(C) Dung Beetle", "(D) Cow"],
    answer: "(C) Dung Beetle",
    category: "general",
  },

  {
    id: 4,
    question: "How many dots appear on a pair of dice?",
    options: ["(A) 21", "(B) 42", "(C) 6", "(D) 1"],
    answer: "(B) 42",
    category: "general",
  },

  {
    id: 5,
    question: "Which is the only body part that is fully grown from birth?",
    options: ["(A) Ear", "(B) Torso", "(C) Eyeball", "(D) Mouth"],
    answer: "(C) Eyeball",
    category: "general",
  },
  {
    id: 6,
    question: "Acrophobia is the fear of?",
    options: ["(A) Space", "(B) Humans", "(C) Height", "(D) Water"],
    answer: "(C) Height",
    category: "general",
  },
  {
    id: 7,
    question: "In what country was Elon Musk born?",
    options: ["(A) Algeria", "(B) England", "(C) France", "(D) South Africa"],
    answer: "(D) South Africa",
    category: "general",
  },
  {
    id: 8,
    question: "Who performs the voice of Homer Simpson? ",
    options: [
      "(A) Chris Evans",
      "(B) Dan Castellaneta",
      "(C) Michael Oliver",
      "(D)Cavil Scott",
    ],
    answer: "(B) Dan Castellaneta",
    category: "general",
  },

  {
    id: 9,
    question: "What is a group of crows called?",
    options: ["(A) Group", "(B) Herds", "(C) Flock", "(D) Murder"],
    answer: "(D) Murder",
    category: "general",
  },
  {
    id: 10,
    question: "How many hearts does an octopus have?",
    options: ["(A) 3", "(B) 2", "(C) 4", "(D) 1"],
    answer: "(A) 3",
    category: "general",
  },
  {
    id: 11,
    question: "December 26th is known by what names in Ireland? ",
    options: [
      "(A) Saint Stephen's Day",
      "(B) Saint James's Day",
      "(C) Saint Joseph's Day",
      "(D) Saint Albert's Day",
    ],
    answer: "(A) Saint Stephen's Day",
    category: "general",
  },
  {
    id: 12,
    question: "In what US state is the country's busiest airport located?",
    options: ["(A) Texas", "(B) California", "(C) Alaska", "(D) Georgia"],
    answer: "(D) Georgia",
    category: "general",
  },
  {
    id: 13,
    question: "Where is the strongest human muscle located?",
    options: ["(A) Spine", "(B) Leg", "(C) Brain", "(D) Jaw"],
    answer: "(D) Jaw",
    category: "general",
  },
  {
    id: 14,
    question: "What phone company produced the 3310?",
    options: ["(A) Apple", "(B) Nokia", "(C) Itel", "(D) Gionee"],
    answer: "(B) Nokia",
    category: "general",
  },

  {
    id: 15,
    question: "What is the chemical symbol for Gold?",
    options: ["(A) Gd", "(B) Go", "(C) Au", "(D) Ag"],
    answer: "(C) Au",
    category: "general",
  },
  {
    id: 16,
    question: "In what year was the first iPhone released?",
    options: ["(A) 2005", "(B) 2007", "(C) 2008", "(D) 2003"],
    answer: "(B) 2007",
    category: "general",
  },
  {
    id: 17,
    question: 'Who painted the "Mona Lisa"?',
    options: [
      "(A) Leonardo da Vinci",
      "(B) Michelangelo",
      "(C) Raphael",
      "(D) Caravaggio",
    ],
    answer: "(A) Leonardo da Vinci",
    category: "general",
  },
  {
    id: 18,
    question: "Who discovered electricity?",
    options: [
      "(A) Isaac Newton",
      "(B) Nikola Tesla",
      "(C) Michael Faraday",
      "(D) Benjamin Franklin",
    ],
    answer: "(D) Benjamin Franklin",
    category: "general",
  },

  {
    id: 19,
    question: "Who came up with the theory of relativity?",
    options: [
      "(A) Edgar Allan",
      "(B) Albert Einstein",
      "(C) Galileo Galilei",
      "(D) Louis Pasteur",
    ],
    answer: "(B) Albert Einstein",
    category: "general",
  },
  {
    id: 20,
    question: "What language is spoken in Brazil?",
    options: ["(A) Spanish", "(B) English", "(C) Portuguese", "(D) French"],
    answer: "(C) Portuguese",
    category: "general",
  },

  {
    id: 21,
    question: " Who invented the lightbulb?",
    options: [
      "(A) Albert Einstein",
      "(B) Nikola Tesla",
      "(C) Graham Bell",
      "(D) Thomas Edison",
    ],
    answer: "(D) Thomas Edison",
    category: "general",
  },

  {
    id: 22,
    question: "Who is the CEO of Tesla?",
    options: [
      "(A) Jeff Bezos",
      "(B) Mark Zuckerberg",
      "(C) Tim Cook",
      "(D) Elon Musk",
    ],
    answer: "(D) Elon Musk",
    category: "general",
  },

  {
    id: 23,
    question: "What is the fastest land animal?",
    options: ["(A) Cheetah", "(B) Ostrich", "(C) Lion", "(D) Tiger"],
    answer: "(A) Cheetah",
    category: "general",
  },
  {
    id: 24,
    question:
      "What animated movie features a rat who dreams of becoming a chef in Paris?",
    options: [
      "(A) Gary The Rat",
      "(B) The Ratties",
      "(C) Ratz",
      "(D) Ratatouille",
    ],
    answer: "(D) Ratatouille",
    category: "entertainment",
  },
  {
    id: 25,
    question:
      " Which actor played Tony Stark/Iron Man in the Marvel Cinematic Universe?",
    options: [
      "(A) Robert Downey Jr",
      "(B) Chris Evans",
      "(C) Chris Hemsworth",
      "(D) Mark Ruffalo",
    ],
    answer: "(A) Robert Downey Jr",
    category: "entertainment",
  },
  {
    id: 26,
    question:
      'What is the name of the fictional continent where "Game of Thrones" primarily takes place?',
    options: [
      "(A) Winterfell",
      "(B) Westeros",
      "(C) Kings Landing",
      "(D) Ballintoy",
    ],
    answer: "(B) Westeros",
    category: "entertainment",
  },
  {
    id: 27,
    question: " Who wrote the Harry Potter book series?",
    options: [
      "(A) E.L James",
      "(B) Stephen King",
      "(C) Ian Fleming",
      "(D) J.K. Rowling",
    ],
    answer: "(D) J.K. Rowling",
    category: "entertainment",
  },
  {
    id: 28,
    question: 'Which pop star is known as the "Queen of Pop"?',
    options: ["(A) Madonna", "(B) Oliver", "(C) Miliano", "(D) Celine"],
    answer: "(A) Madonna",
    category: "entertainment",
  },
  {
    id: 29,
    question:
      "What is the name of the fictional African country in Black Panther?",
    options: ["(A) Mbube", "(B) Wakanda", "(C) Iron Throne", "(D) Westeros"],
    answer: "(B) Wakanda",
    category: "entertainment",
  },
  {
    id: 30,
    question: "Which actor played Jack Dawson in Titanic?",
    options: [
      "(A) Victor Garber",
      "(B) Bill Paxton",
      "(C) Billy Zane",
      "(D) Leonardo DiCaprio",
    ],
    answer: "(D) Leonardo DiCaprio",
    category: "entertainment",
  },
  {
    id: 31,
    question:
      "What is the highest-grossing animated film of all time as at 2023? ",
    options: ["(A) Lion King", "(B) Moana", "(C) Frozen II", "(D) Sing"],
    answer: "(C) Frozen II",
    category: "entertainment",
  },
  {
    id: 32,
    question: "What kind of animal is Shrek?",
    options: ["(A) Donkey", "(B) Dragon", "(C) Ogre", "(D) Giant"],
    answer: "(C) Ogre",
    category: "entertainment",
  },
  {
    id: 33,
    question: "What country has won the most World Cups?",
    options: ["(A) Brazil", "(B) Italy", "(C) Argentina", "(D) Spain"],
    answer: "(A) Brazil",
    category: "sport",
  },
  {
    id: 34,
    question: "In what city is the NFL Hall of Fame located?",
    options: ["(A) New York", "(B) Manchester", "(C) London", "(D) Ohio"],
    answer: "(D) Ohio",
    category: "sport",
  },
  {
    id: 35,
    question: "Simone Biles is famous for her skill in what sport?",
    options: [
      "(A) Gymnastics",
      "(B) Football",
      "(C) Basketball",
      "(D) Table Tennis",
    ],
    answer: "(A) Gymnastics",
    category: "sport",
  },
  {
    id: 36,
    question: "What was the first name of Argentinian soccer star Maradona?",
    options: ["(A) Lionel", "(B) Diego", "(C) Angel", "(D) Diogo"],
    answer: "(B) Diego",
    category: "sport",
  },
  {
    id: 37,
    question: "What height is a regulation NBA basket?  ",
    options: ["(A) 12 feet", "(B) 9 feet", "(C) 10 feet", "(D) 8 feet"],
    answer: "(C) 10 feet",
    category: "sport",
  },
  {
    id: 38,
    question: "What is the national sport of Japan?",
    options: [
      "(A) Sumo Boxing",
      "(B) Danju Wrestling",
      "(C) Danju Boxing",
      "(D) Sumo Wrestling",
    ],
    answer: "(D) Sumo Wrestling",
    category: "sport",
  },
  {
    id: 39,
    question: "What sporting event has a strict dress code of all-white?",
    options: ["(A) Marathon", "(B) Wimbledon", "(C) Jupitar", "(D) Olympics"],
    answer: "(B) Wimbledon",
    category: "sport",
  },
  {
    id: 40,
    question: "How many players are there in a soccer team?",
    options: ["(A) 10", "(B) 11", "(C) 7", "(D) 5"],
    answer: "(B) 11",
    category: "sport",
  },
  {
    id: 41,
    question: "Which planet in the Milky Way is the hottest?",
    options: ["(A) Earth", "(B) Venus", "(C) Pluto", "(D) Mars"],
    answer: "(B) Venus",
    category: "geography",
  },
  {
    id: 42,
    question: "What planet is closest to the sun?",
    options: ["(A) Earth", "(B) Venus", "(C) Mercury", "(D) Mars"],
    answer: "(C) Mercury",
    category: "geography",
  },
  {
    id: 43,
    question: "Which planet has the most moons?",
    options: ["(A) Saturn", "(B) Venus", "(C) Pluto", "(D) Mars"],
    answer: "(A) Saturn",
    category: "geography",
  },
  {
    id: 44,
    question: "What country has the most islands? ",
    options: ["(A) Sweden", "(B) India", "(C) Ukrain", "(D) Ireland"],
    answer: "(A) Sweden",
    category: "geography",
  },
  {
    id: 45,
    question: "What is the only continent with land in all four hemispheres?",
    options: ["(A) Africa", "(B) Europe", "(C) America", "(D) Asia"],
    answer: "(A) Africa",
    category: "geography",
  },
  {
    id: 46,
    question: "Which river flows through the Grand Canyon?",
    options: [
      "(A) Congo River",
      "(B) Colorado River",
      "(C) Chari River",
      "(D) Nile River",
    ],
    answer: "(B) Colorado River",
    category: "geography",
  },
  {
    id: 47,
    question: "Where is Angel Falls, the world’s largest waterfall located?",
    options: ["(A) Sweden", "(B) Ireland", "(C) Venezuela", "(D) England"],
    answer: "(C) Venezuela",
    category: "geography",
  },
  {
    id: 48,
    question: "What is the state capital of New York?",
    options: ["(A) Denver", "(B) Phoenix", "(C) Atlanta", "(D) Albany"],
    answer: "(D) Albany",
    category: "geography",
  },
  {
    id: 49,
    question: "What is the capital of Ireland?",
    options: ["(A) Juneau", "(B) Hartford", "(C) Boise", "(D) Dublin"],
    answer: "(D) Dublin",
    category: "geography",
  },
  {
    id: 50,
    question: "What is the smallest US state by area?",
    options: ["(A) Ohio", "(B) Rhode Island", "(C) Texas", "(D) Alaska"],
    answer: "(B) Rhode Island",
    category: "geography",
  },
  {
    id: 51,
    question: "What is the tallest type of tree?",
    options: ["(A) Oak", "(B) Hawthorn", "(C) Redwoods", "(D) Black Locust"],
    answer: "(C) Redwoods",
    category: "geography",
  },
  {
    id: 52,
    question: "Holland is a region in The Netherlands?",
    options: ["(A) True", "(B) False"],
    answer: "(A) True",
    category: "geography",
  },
  {
    id: 53,
    question: "How many European capitals does the Danube flow through?",
    options: ["(A) 4", "(B) 1", "(C) 3", "(D) 5"],
    answer: "(A) 4",
    category: "geography",
  },
  {
    id: 54,
    question: "What is the capital of Canada?",
    options: ["(A) Phoenix", "(B) Ottawa", "(C) Atlanta", "(D) Denver"],
    answer: "(B) Ottawa",
    category: "geography",
  },
  {
    id: 55,
    question: "In what capital would you find The Little Mermaid statue?",
    options: ["(A) Hartford", "(B) Dublin", "(C) Copenhagen", "(D) Juneau"],
    answer: "(C) Copenhagen",
    category: "geography",
  },
  {
    id: 56,
    question: "In what continent would you find the city of Baku?",
    options: ["(A) America", "(B) Italy", "(C) Russia", "(D) Asia"],
    answer: "(D) Asia",
    category: "geography",
  },
  {
    id: 57,
    question: "How many stars are on the Chinese flag?",
    options: ["(A) 5", "(B) 4", "(C) 3", "(D) 6"],
    answer: "(A) 5",
    category: "geography",
  },
  {
    id: 58,
    question: "How many colors are used in the South African flag?",
    options: ["(A) 5", "(B) 4", "(C) 3", "(D) 6"],
    answer: "(D) 6",
    category: "geography",
  },
  {
    id: 59,
    question: "What is the tallest mountain in the world?",
    options: [
      "(A) k2",
      "(B) Mount Everest",
      "(C) Mount Kilimanjaro",
      "(D) Denali",
    ],
    answer: "(B) Mount Everest",
    category: "geography",
  },
  {
    id: 60,
    question: ' Which planet is known as the "Red Planet"?',
    options: ["(A) Venus", "(B) Mars", "(C) Juital", "(D) Saturn"],
    answer: "(B) Mars",
    category: "geography",
  },
  {
    id: 61,
    question: "What is the world's largest ocean?",
    options: [
      "(A) Atlantic Ocean",
      "(B) Indian Ocean",
      "(C) Pacific Ocean",
      "(D) Southern Ocean",
    ],
    answer: "(C) Pacific Ocean",
    category: "geography",
  },

  {
    id: 62,
    question: "What is the hottest planet in the solar system?",
    options: ["(A) Mercury", "(B) Mars", "(C) Venus", "(D) Jupital"],
    answer: "(C) Venus",
    category: "geography",
  },
];
